# Generated by Django 3.2.5 on 2022-09-29 19:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=254, verbose_name='First name')),
                ('middle_name', models.CharField(blank=True, max_length=254, null=True, verbose_name='Middle name')),
                ('last_name', models.CharField(blank=True, max_length=254, null=True, verbose_name='Last name')),
                ('phone', models.CharField(help_text='Example +255714112233', max_length=14, unique=True, validators=[django.core.validators.RegexValidator('^(\\+\\d{1,3})?,?\\s?\\d{8,13}')], verbose_name='Phone Number')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('memberId', models.SlugField(editable=False, unique=True, verbose_name='Membership Identification')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=8, verbose_name='Gender')),
                ('region', models.CharField(choices=[('Arusha', 'Arusha'), ('Dar es Salaam', 'Dar es Salaam'), ('Dodoma', 'Dodoma'), ('Geita', 'Geita'), ('Iringa', 'Iringa'), ('Kagera', 'Kagera'), ('Katavi', 'Katavi'), ('Kigoma', 'Kigoma'), ('Kilimanjaro', 'Kilimanjaro'), ('Lindi', 'Lindi'), ('Manyara', 'Manyara'), ('Mara', 'Mara'), ('Mbeya', 'Mbeya'), ('Mjini Magharibi', 'Mjini Magharibi'), ('Morogoro', 'Morogoro'), ('Mtwara', 'Mtwara'), ('Mwanza', 'Mwanza'), ('Njombe', 'Njombe'), ('Pemba North', 'Pemba North'), ('Pemba South', 'Pemba South'), ('Pwani', 'Pwani'), ('Rukwa', 'Rukwa'), ('Ruvuma', 'Ruvuma'), ('Shinyanga', 'Shinyanga'), ('Simiyu', 'Simiyu'), ('Singida', 'Singida'), ('Songwe', 'Songwe'), ('Tabora', 'Tabora'), ('Tanga', 'Tanga'), ('Unguja North', 'Unguja North'), ('Unguja South', 'Unguja South')], max_length=50, verbose_name='Region')),
                ('organization', models.CharField(max_length=180, verbose_name='Your Organization')),
                ('profession', models.CharField(choices=[('Administrator', 'Administrator'), ('Community health worker', 'ommunity health worker'), ('First responder such as EMT or Paramedic', 'First responder such as EMT or Paramedic'), ('Medical doctor', 'Medical doctor'), ('Mental health provider such as counselor, psychologist, social worker', 'Mental health provider such as counselor, psychologist, social worker'), ('Nurse or practitioner or physician assistant', 'Nurse or practitioner or physician assistant'), ('Pharmacist', 'Pharmacist'), ('Paediatrician', 'Paediatrician'), ('Public health official', 'Public health official'), ('Testing or laboratory personnel', 'Testing or laboratory personnel'), ('Teacher/educator', 'Teacher/educator'), ('Researcher', 'Researcher'), ('Student', 'Student'), ('Other', 'Other')], max_length=180, verbose_name='Your Profession')),
                ('areaofwork', models.CharField(choices=[('Work', 'Work'), ('Hospital', 'Hospital'), ('Community healthcare', 'Community healthcare'), ('Nursing/care facility', 'Nursing/care facility'), ('Non-governmental organization', 'Non-governmental organization'), ('School/university', 'School/university'), ('Government', 'Government'), ('Others', 'Others')], max_length=180, verbose_name='Area of work')),
                ('typeofmember', models.CharField(choices=[('Associate Member', 'Associate Member'), ('Ordinary Member', 'Ordinary Member')], max_length=180, verbose_name='Membership type')),
                ('mctnumber', models.CharField(blank=True, max_length=50, null=True, verbose_name='MCT Number')),
                ('avatar', django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default.jpg', force_format=None, keep_meta=True, quality=-1, scale=None, size=[300, 300], upload_to='profile/images/%Y/%m/%d', verbose_name='Profile Image')),
                ('collage', models.CharField(blank=True, max_length=180, null=True, verbose_name='Collage that you had your masters')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Year that you graduated')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('membership_type', models.CharField(choices=[('Associate Plan', 'Associate Plan'), ('Ordinary Plan', 'Ordinary Plan')], default='Associate Plan', max_length=30)),
                ('price', models.IntegerField(default=15)),
                ('planId', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='UserMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='membership.membership')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=15)),
                ('created', models.DateTimeField(verbose_name='Paid at')),
                ('expire', models.DateTimeField(verbose_name='Paid at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
