# Generated by Django 3.2.5 on 2022-09-27 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='typeofmember',
            field=models.CharField(choices=[('Associate Member', 'Associate Member'), ('Ordinary Member', 'Ordinary Member')], default='Associate Member', max_length=180, verbose_name='Membership type'),
        ),
    ]
