# Generated by Django 3.2.5 on 2022-09-12 23:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_membership_paymentdate_subscription_usermembership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mctnumber',
            field=models.CharField(max_length=50, unique=True, verbose_name='MCT Number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='memberId',
            field=models.SlugField(editable=False, unique=True, verbose_name='Membership Identification'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='profession',
            field=models.CharField(choices=[('Administrator', 'Administrator'), ('Community health worker', 'ommunity health worker'), ('First responder such as EMT or Paramedic', 'First responder such as EMT or Paramedic'), ('Medical doctor', 'Medical doctor'), ('Mental health provider such as counselor, psychologist, social worker', 'Mental health provider such as counselor, psychologist, social worker'), ('Nurse or practitioner or physician assistant', 'Nurse or practitioner or physician assistant'), ('Pharmacist', 'Pharmacist'), ('Paediatrician', 'Paediatrician'), ('Public health official', 'Public health official'), ('Testing or laboratory personnel', 'Testing or laboratory personnel'), ('Teacher/educator', 'Teacher/educator'), ('Researcher', 'Researcher'), ('Student', 'Student'), ('Other', 'Other')], max_length=180, verbose_name='Your Profession'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='default.jpg', upload_to='uploads/profile/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
