# Generated by Django 3.2.5 on 2022-09-20 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0004_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='default.jpg', upload_to='uploads/profile/'),
        ),
        migrations.AddField(
            model_name='user',
            name='collage',
            field=models.CharField(blank=True, max_length=180, null=True, verbose_name='Collage that you had your masters'),
        ),
        migrations.AddField(
            model_name='user',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Year that you graduated'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
