# Generated by Django 3.2.5 on 2022-09-20 13:25

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0005_auto_20220920_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default.jpg', force_format=None, keep_meta=True, quality=-1, scale=None, size=[300, 300], upload_to='product/images/%Y/%m/%d', verbose_name='Profile Image'),
        ),
    ]
