# Generated by Django 3.2.5 on 2022-09-21 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0006_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mctnumber',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='MCT Number'),
        ),
    ]
