# Generated by Django 3.2.5 on 2022-09-22 12:08

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0007_alter_user_mctnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default.jpg', force_format=None, keep_meta=True, quality=-1, scale=None, size=[300, 300], upload_to='profile/images/%Y/%m/%d', verbose_name='Profile Image'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mctnumber',
            field=models.CharField(blank=True, max_length=50, verbose_name='MCT Number'),
        ),
    ]
