# Generated by Django 3.2.5 on 2022-08-28 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectname', models.CharField(max_length=150, verbose_name='Project Name')),
                ('startdate', models.DateField(verbose_name='Starting Date')),
                ('shortdescription', models.TextField(verbose_name='Short Description')),
                ('specificObjective', models.TextField(verbose_name='Specific Objective')),
                ('enddate', models.DateField(verbose_name='End Date')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='ProjectGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(max_length=150, verbose_name='Project Goal')),
                ('results', models.CharField(max_length=180, verbose_name='Project Result')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project', verbose_name='')),
            ],
            options={
                'verbose_name': 'project goal',
                'verbose_name_plural': 'project goals',
            },
        ),
    ]
