# Generated by Django 3.2.5 on 2022-09-02 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectdonor',
            options={'verbose_name': 'Project Donor', 'verbose_name_plural': 'Projects Donors'},
        ),
        migrations.AlterField(
            model_name='project',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectdonor', to='project.projectdonor', verbose_name='Project Donor'),
        ),
        migrations.AlterField(
            model_name='projectgoal',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='project.project', verbose_name='Project'),
        ),
    ]
