# Generated by Django 3.2.5 on 2022-11-19 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, verbose_name='Conference Name')),
                ('slug', models.SlugField(editable=False, unique=True, verbose_name='Slug')),
                ('shortdescription', models.TextField(verbose_name='Short Description')),
                ('resolution', models.FileField(upload_to='AGM/', verbose_name='Resolution')),
                ('presentation', models.URLField(verbose_name='Presentations')),
                ('images', models.URLField(verbose_name='Images')),
                ('abstract', models.FileField(upload_to=None, verbose_name='Abstract Book')),
                ('cover', models.ImageField(upload_to='agm/cover/', verbose_name='Project Cover Image')),
                ('attendance', models.IntegerField(verbose_name='Number of Attendance')),
                ('startdate', models.DateField(verbose_name='Start Date')),
                ('enddate', models.DateField(verbose_name='End Date')),
            ],
            options={
                'verbose_name': 'Conference',
                'verbose_name_plural': 'Conferences',
            },
        ),
    ]
