# Generated by Django 3.2.5 on 2022-11-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='theme',
            field=models.CharField(default='conference theme', max_length=180, verbose_name='Conference Theme'),
        ),
        migrations.AddField(
            model_name='conference',
            name='venue',
            field=models.CharField(default='conference venue', max_length=180, verbose_name='Conference Venue and Location'),
        ),
    ]
