# Generated by Django 3.2.5 on 2022-10-29 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.CharField(max_length=150, verbose_name='Request Name')),
                ('slug', models.SlugField(editable=False, unique=True, verbose_name='Slug')),
                ('requestdate', models.DateField(verbose_name='Requesting Date')),
                ('description', models.TextField(verbose_name='Description')),
                ('approveddate', models.DateField(verbose_name='End Date')),
                ('approvedby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvedBy', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donor', to='project.projectdonor', verbose_name='Project Donor')),
                ('requestedbby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requestedBy', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Request',
                'verbose_name_plural': 'Activity Requests',
            },
        ),
        migrations.CreateModel(
            name='ActivityRequestDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=160, verbose_name='Service or Product')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('frequency', models.IntegerField(verbose_name='Frequency')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='earequest.activityrequest', verbose_name='Activity')),
            ],
        ),
    ]
