# Generated by Django 3.2.5 on 2022-11-08 22:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('earequest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityrequest',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='approved'),
        ),
        migrations.AddField(
            model_name='activityrequest',
            name='declined',
            field=models.BooleanField(default=False, verbose_name='declined'),
        ),
        migrations.AlterField(
            model_name='activityrequest',
            name='approvedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approvedBy', to=settings.AUTH_USER_MODEL),
        ),
    ]
