# Generated by Django 3.2.5 on 2022-11-09 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earequest', '0002_auto_20221108_2254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityrequest',
            name='request',
        ),
        migrations.RemoveField(
            model_name='activityrequest',
            name='slug',
        ),
        migrations.AlterField(
            model_name='activityrequestdetails',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price Amount'),
        ),
    ]
