# Generated by Django 3.2.5 on 2022-11-24 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('earequest', '0004_auto_20221111_1429'),
        ('earequest', '0004_auto_20221116_1023'),
    ]

    operations = [
    ]
