# Generated by Django 3.2.5 on 2022-11-25 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('earequest', '0005_merge_0004_auto_20221111_1429_0004_auto_20221116_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityrequest',
            name='approveddate',
            field=models.DateField(blank=True, null=True, verbose_name='Approved Date'),
        ),
        migrations.AlterField(
            model_name='activityrequestdetails',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='earequest.activityrequest', verbose_name='Activity'),
        ),
    ]
