# Generated by Django 3.2.5 on 2022-08-30 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='Document Name')),
                ('slug', models.SlugField(editable=False, unique=True, verbose_name='Slug')),
                ('file', models.FileField(upload_to='uploads/documents', verbose_name='File Name')),
                ('published', models.BooleanField(default=False, verbose_name='Published')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Created at')),
                ('description', models.TextField(verbose_name='Descriptions')),
                ('downloads', models.IntegerField(default=0, verbose_name='Number Downloads')),
            ],
            options={
                'verbose_name': 'Resource',
                'verbose_name_plural': 'Resources',
            },
        ),
    ]
