# Generated by Django 3.2.5 on 2022-09-02 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='Category Name')),
                ('slug', models.SlugField(editable=False, unique=True, verbose_name='Slug')),
            ],
        ),
        migrations.AddField(
            model_name='resource',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='resources.ResourceCategory', verbose_name='Product Category'),
        ),
    ]
