# Generated by Django 3.2.5 on 2022-08-29 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Published'),
        ),
    ]
