# Generated by Django 3.2.5 on 2022-08-30 22:09

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Updates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='Title')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('cover', models.ImageField(upload_to='blog/covers/', verbose_name='Cover Image')),
                ('content', django_quill.fields.QuillField()),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Created at')),
                ('downloads', models.IntegerField(default=0, verbose_name='Number Downloads')),
            ],
            options={
                'verbose_name': 'Updates',
                'verbose_name_plural': 'Updatess',
            },
        ),
    ]
