# Generated by Django 3.2.5 on 2022-09-12 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updates',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='updates',
            name='downloads',
            field=models.IntegerField(default=0, editable=False, verbose_name='Number Of Views'),
        ),
        migrations.AlterField(
            model_name='updates',
            name='slug',
            field=models.SlugField(editable=False, unique=True, verbose_name='Slug'),
        ),
    ]
