# Generated by Django 3.2.5 on 2022-09-23 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0002_auto_20220912_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='updates',
            name='membersonly',
            field=models.BooleanField(default=False, verbose_name='Members only'),
        ),
    ]
